# Generated by Django 4.2.7 on 2026-06-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_file_optional'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['user', '-created_at'], name='videos_vide_user_id_260722_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-view_count'], name='videos_vide_view_co_02bc14_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-like_count'], name='videos_vide_like_co_f8ad1d_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['cloudinary_public_id'], name='videos_vide_cloudin_ab4844_idx'),
        ),
    ]
